package initialize

import (
	"eva/global"
	"eva/model/book"
	"eva/model/common"
	"eva/model/file_upload"
	"eva/model/memorandum"
	"eva/model/system"
	"go.uber.org/zap"
	"gorm.io/gorm"
	"os"
)

// Gorm 初始化数据库并产生数据库全局变量
// Author SliverHorn
func Gorm() *gorm.DB {
	switch global.EVA_CONFIG.System.DbType {
	case "mysql":
		return GormMysql()
	case "pgsql":
		return GormPgSql()
	default:
		return GormMysql()
	}
}

// RegisterTables 注册数据库表专用
// Author SliverHorn
func RegisterTables(db *gorm.DB) {
	err := db.AutoMigrate(
		// 系统模块表
		system.SysUser{},
		system.SysOperationRecord{},

		// 公共模块
		file_upload.ExaFileUploadAndDownload{},
		common.Banner{},

		// book模块
		book.BookInfo{},
		book.BookLabel{},
		book.BookType{},
		book.BookChapter{},

		// 备忘录模块
		memorandum.MemorandumTopic{},
		memorandum.Memorandum{},

		// Code generated by eva End; DO NOT EDIT.
	)
	if err != nil {
		global.EVA_LOG.Error("register table failed", zap.Error(err))
		os.Exit(0)
	}
	global.EVA_LOG.Info("register table success")
}
