package initialize

import (
	"eva/global"
	"eva/model/book"
	"eva/model/example"
	"go.uber.org/zap"
	"gorm.io/gorm"
	"os"
)

// Gorm 初始化数据库并产生数据库全局变量
// Author SliverHorn
func Gorm() *gorm.DB {
	switch global.EVA_CONFIG.System.DbType {
	case "mysql":
		return GormMysql()
	case "pgsql":
		return GormPgSql()
	default:
		return GormMysql()
	}
}

// RegisterTables 注册数据库表专用
// Author SliverHorn
func RegisterTables(db *gorm.DB) {
	err := db.AutoMigrate(
		// 系统模块表

		// 公共模块
		example.ExaFileUploadAndDownload{},

		// book模块
		book.BookInfo{},
		book.Label{},
		book.Type{},
		book.Chapter{},

		// Code generated by eva End; DO NOT EDIT.
	)
	if err != nil {
		global.EVA_LOG.Error("register table failed", zap.Error(err))
		os.Exit(0)
	}
	global.EVA_LOG.Info("register table success")
}
