// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.21.5
// source: idl/proto/private/calendar_job/jobModels.proto

package private_pd

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JobModel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"job_id"
	JobID uint64 `protobuf:"varint,1,opt,name=JobID,proto3" json:"JobID,omitempty"`
	// @inject_tag: json:"user_id"
	UserID uint64 `protobuf:"varint,2,opt,name=UserID,proto3" json:"UserID,omitempty"`
	// @inject_tag: json:"status"
	Status uint32 `protobuf:"varint,3,opt,name=Status,proto3" json:"Status,omitempty"`
	// @inject_tag: json:"title"
	Title string `protobuf:"bytes,4,opt,name=Title,proto3" json:"Title,omitempty"`
	// @inject_tag: json:"content"
	Content string `protobuf:"bytes,5,opt,name=Content,proto3" json:"Content,omitempty"`
	// @inject_tag: json:"notice_time"
	NoticeTime string `protobuf:"bytes,6,opt,name=NoticeTime,proto3" json:"NoticeTime,omitempty"`
	// @inject_tag: json:"phone"
	Phone *string `protobuf:"bytes,7,opt,name=Phone,proto3,oneof" json:"Phone,omitempty"`
	// @inject_tag: json:"email"
	Email string `protobuf:"bytes,8,opt,name=Email,proto3" json:"Email,omitempty"`
	// @inject_tag: json:"wechat"
	WeChat   *string `protobuf:"bytes,9,opt,name=WeChat,proto3,oneof" json:"WeChat,omitempty"`
	RecordID uint64  `protobuf:"varint,10,opt,name=RecordID,proto3" json:"RecordID,omitempty"`
}

func (x *JobModel) Reset() {
	*x = JobModel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_proto_private_calendar_job_jobModels_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JobModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobModel) ProtoMessage() {}

func (x *JobModel) ProtoReflect() protoreflect.Message {
	mi := &file_idl_proto_private_calendar_job_jobModels_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobModel.ProtoReflect.Descriptor instead.
func (*JobModel) Descriptor() ([]byte, []int) {
	return file_idl_proto_private_calendar_job_jobModels_proto_rawDescGZIP(), []int{0}
}

func (x *JobModel) GetJobID() uint64 {
	if x != nil {
		return x.JobID
	}
	return 0
}

func (x *JobModel) GetUserID() uint64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *JobModel) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *JobModel) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *JobModel) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *JobModel) GetNoticeTime() string {
	if x != nil {
		return x.NoticeTime
	}
	return ""
}

func (x *JobModel) GetPhone() string {
	if x != nil && x.Phone != nil {
		return *x.Phone
	}
	return ""
}

func (x *JobModel) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *JobModel) GetWeChat() string {
	if x != nil && x.WeChat != nil {
		return *x.WeChat
	}
	return ""
}

func (x *JobModel) GetRecordID() uint64 {
	if x != nil {
		return x.RecordID
	}
	return 0
}

var File_idl_proto_private_calendar_job_jobModels_proto protoreflect.FileDescriptor

var file_idl_proto_private_calendar_job_jobModels_proto_rawDesc = []byte{
	0x0a, 0x2e, 0x69, 0x64, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x72, 0x69, 0x76,
	0x61, 0x74, 0x65, 0x2f, 0x63, 0x61, 0x6c, 0x65, 0x6e, 0x64, 0x61, 0x72, 0x5f, 0x6a, 0x6f, 0x62,
	0x2f, 0x6a, 0x6f, 0x62, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x9f, 0x02, 0x0a, 0x08, 0x4a, 0x6f, 0x62, 0x4d,
	0x6f, 0x64, 0x65, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x4a, 0x6f, 0x62, 0x49, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x05, 0x4a, 0x6f, 0x62, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72,
	0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x69,
	0x74, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x4e, 0x6f,
	0x74, 0x69, 0x63, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x4e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x19, 0x0a, 0x05, 0x50, 0x68,
	0x6f, 0x6e, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x05, 0x50, 0x68, 0x6f,
	0x6e, 0x65, 0x88, 0x01, 0x01, 0x12, 0x14, 0x0a, 0x05, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x1b, 0x0a, 0x06, 0x57,
	0x65, 0x43, 0x68, 0x61, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x06, 0x57,
	0x65, 0x43, 0x68, 0x61, 0x74, 0x88, 0x01, 0x01, 0x12, 0x1a, 0x0a, 0x08, 0x52, 0x65, 0x63, 0x6f,
	0x72, 0x64, 0x49, 0x44, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x52, 0x65, 0x63, 0x6f,
	0x72, 0x64, 0x49, 0x44, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x42, 0x09,
	0x0a, 0x07, 0x5f, 0x57, 0x65, 0x43, 0x68, 0x61, 0x74, 0x42, 0x23, 0x5a, 0x21, 0x2e, 0x2f, 0x70,
	0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2f, 0x63, 0x61, 0x6c, 0x65, 0x6e, 0x64, 0x61, 0x72, 0x5f,
	0x6a, 0x6f, 0x62, 0x3b, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x5f, 0x70, 0x64, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_idl_proto_private_calendar_job_jobModels_proto_rawDescOnce sync.Once
	file_idl_proto_private_calendar_job_jobModels_proto_rawDescData = file_idl_proto_private_calendar_job_jobModels_proto_rawDesc
)

func file_idl_proto_private_calendar_job_jobModels_proto_rawDescGZIP() []byte {
	file_idl_proto_private_calendar_job_jobModels_proto_rawDescOnce.Do(func() {
		file_idl_proto_private_calendar_job_jobModels_proto_rawDescData = protoimpl.X.CompressGZIP(file_idl_proto_private_calendar_job_jobModels_proto_rawDescData)
	})
	return file_idl_proto_private_calendar_job_jobModels_proto_rawDescData
}

var file_idl_proto_private_calendar_job_jobModels_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_idl_proto_private_calendar_job_jobModels_proto_goTypes = []interface{}{
	(*JobModel)(nil), // 0: proto.JobModel
}
var file_idl_proto_private_calendar_job_jobModels_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_idl_proto_private_calendar_job_jobModels_proto_init() }
func file_idl_proto_private_calendar_job_jobModels_proto_init() {
	if File_idl_proto_private_calendar_job_jobModels_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_idl_proto_private_calendar_job_jobModels_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JobModel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_idl_proto_private_calendar_job_jobModels_proto_msgTypes[0].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_idl_proto_private_calendar_job_jobModels_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_idl_proto_private_calendar_job_jobModels_proto_goTypes,
		DependencyIndexes: file_idl_proto_private_calendar_job_jobModels_proto_depIdxs,
		MessageInfos:      file_idl_proto_private_calendar_job_jobModels_proto_msgTypes,
	}.Build()
	File_idl_proto_private_calendar_job_jobModels_proto = out.File
	file_idl_proto_private_calendar_job_jobModels_proto_rawDesc = nil
	file_idl_proto_private_calendar_job_jobModels_proto_goTypes = nil
	file_idl_proto_private_calendar_job_jobModels_proto_depIdxs = nil
}
