// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.21.5
// source: idl/proto/private/privvate.proto

package proto

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AutoLabelReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProjectId      int64    `protobuf:"varint,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	DirId          int64    `protobuf:"varint,2,opt,name=dir_id,json=dirId,proto3" json:"dir_id,omitempty"`
	FilterLabel    []string `protobuf:"bytes,3,rep,name=filter_label,json=filterLabel,proto3" json:"filter_label,omitempty"`
	FilterPriority []string `protobuf:"bytes,4,rep,name=filter_priority,json=filterPriority,proto3" json:"filter_priority,omitempty"`
	AddLabel       []string `protobuf:"bytes,5,rep,name=add_label,json=addLabel,proto3" json:"add_label,omitempty"`
	AddPriority    *string  `protobuf:"bytes,6,opt,name=add_priority,json=addPriority,proto3,oneof" json:"add_priority,omitempty"`
	RemoveLabel    []string `protobuf:"bytes,7,rep,name=remove_label,json=removeLabel,proto3" json:"remove_label,omitempty"`
}

func (x *AutoLabelReq) Reset() {
	*x = AutoLabelReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_proto_private_privvate_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AutoLabelReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AutoLabelReq) ProtoMessage() {}

func (x *AutoLabelReq) ProtoReflect() protoreflect.Message {
	mi := &file_idl_proto_private_privvate_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AutoLabelReq.ProtoReflect.Descriptor instead.
func (*AutoLabelReq) Descriptor() ([]byte, []int) {
	return file_idl_proto_private_privvate_proto_rawDescGZIP(), []int{0}
}

func (x *AutoLabelReq) GetProjectId() int64 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

func (x *AutoLabelReq) GetDirId() int64 {
	if x != nil {
		return x.DirId
	}
	return 0
}

func (x *AutoLabelReq) GetFilterLabel() []string {
	if x != nil {
		return x.FilterLabel
	}
	return nil
}

func (x *AutoLabelReq) GetFilterPriority() []string {
	if x != nil {
		return x.FilterPriority
	}
	return nil
}

func (x *AutoLabelReq) GetAddLabel() []string {
	if x != nil {
		return x.AddLabel
	}
	return nil
}

func (x *AutoLabelReq) GetAddPriority() string {
	if x != nil && x.AddPriority != nil {
		return *x.AddPriority
	}
	return ""
}

func (x *AutoLabelReq) GetRemoveLabel() []string {
	if x != nil {
		return x.RemoveLabel
	}
	return nil
}

type AutoLabelResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId   string    `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Percent  int32     `protobuf:"varint,2,opt,name=percent,proto3" json:"percent,omitempty"`
	BaseResp *BaseResp `protobuf:"bytes,3,opt,name=base_resp,json=baseResp,proto3" json:"base_resp,omitempty"`
}

func (x *AutoLabelResp) Reset() {
	*x = AutoLabelResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_proto_private_privvate_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AutoLabelResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AutoLabelResp) ProtoMessage() {}

func (x *AutoLabelResp) ProtoReflect() protoreflect.Message {
	mi := &file_idl_proto_private_privvate_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AutoLabelResp.ProtoReflect.Descriptor instead.
func (*AutoLabelResp) Descriptor() ([]byte, []int) {
	return file_idl_proto_private_privvate_proto_rawDescGZIP(), []int{1}
}

func (x *AutoLabelResp) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *AutoLabelResp) GetPercent() int32 {
	if x != nil {
		return x.Percent
	}
	return 0
}

func (x *AutoLabelResp) GetBaseResp() *BaseResp {
	if x != nil {
		return x.BaseResp
	}
	return nil
}

type BaseResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *BaseResp) Reset() {
	*x = BaseResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_proto_private_privvate_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BaseResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseResp) ProtoMessage() {}

func (x *BaseResp) ProtoReflect() protoreflect.Message {
	mi := &file_idl_proto_private_privvate_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseResp.ProtoReflect.Descriptor instead.
func (*BaseResp) Descriptor() ([]byte, []int) {
	return file_idl_proto_private_privvate_proto_rawDescGZIP(), []int{2}
}

func (x *BaseResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *BaseResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_idl_proto_private_privvate_proto protoreflect.FileDescriptor

var file_idl_proto_private_privvate_proto_rawDesc = []byte{
	0x0a, 0x20, 0x69, 0x64, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x72, 0x69, 0x76,
	0x61, 0x74, 0x65, 0x2f, 0x70, 0x72, 0x69, 0x76, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x21, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x89, 0x02, 0x0a,
	0x0c, 0x41, 0x75, 0x74, 0x6f, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x12, 0x1d, 0x0a,
	0x0a, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x64, 0x12, 0x15, 0x0a, 0x06,
	0x64, 0x69, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x64, 0x69,
	0x72, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x5f, 0x6c, 0x61,
	0x62, 0x65, 0x6c, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b, 0x66, 0x69, 0x6c, 0x74, 0x65,
	0x72, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x12, 0x27, 0x0a, 0x0f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72,
	0x5f, 0x70, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x0e, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x50, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x12,
	0x1b, 0x0a, 0x09, 0x61, 0x64, 0x64, 0x5f, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x18, 0x05, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x08, 0x61, 0x64, 0x64, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x12, 0x26, 0x0a, 0x0c,
	0x61, 0x64, 0x64, 0x5f, 0x70, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x48, 0x00, 0x52, 0x0b, 0x61, 0x64, 0x64, 0x50, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74,
	0x79, 0x88, 0x01, 0x01, 0x12, 0x21, 0x0a, 0x0c, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x5f, 0x6c,
	0x61, 0x62, 0x65, 0x6c, 0x18, 0x07, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x65, 0x6d, 0x6f,
	0x76, 0x65, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x42, 0x0f, 0x0a, 0x0d, 0x5f, 0x61, 0x64, 0x64, 0x5f,
	0x70, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x22, 0x70, 0x0a, 0x0d, 0x41, 0x75, 0x74, 0x6f,
	0x4c, 0x61, 0x62, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x61, 0x73,
	0x6b, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b,
	0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x07, 0x70, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x12, 0x2c, 0x0a, 0x09,
	0x62, 0x61, 0x73, 0x65, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x52, 0x08, 0x62, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x22, 0x30, 0x0a, 0x08, 0x42, 0x61,
	0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73,
	0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x32, 0x69, 0x0a, 0x09,
	0x41, 0x75, 0x74, 0x6f, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x12, 0x5c, 0x0a, 0x10, 0x41, 0x75, 0x74,
	0x6f, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x41, 0x64, 0x64, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x13, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x75, 0x74, 0x6f, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x52,
	0x65, 0x71, 0x1a, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x75, 0x74, 0x6f, 0x4c,
	0x61, 0x62, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x22, 0x1d, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x17,
	0x22, 0x12, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x32, 0x2f, 0x61, 0x75, 0x74, 0x6f, 0x5f, 0x6c,
	0x61, 0x62, 0x65, 0x6c, 0x3a, 0x01, 0x2a, 0x42, 0x10, 0x5a, 0x0e, 0x2e, 0x2f, 0x62, 0x79, 0x74,
	0x65, 0x73, 0x74, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_idl_proto_private_privvate_proto_rawDescOnce sync.Once
	file_idl_proto_private_privvate_proto_rawDescData = file_idl_proto_private_privvate_proto_rawDesc
)

func file_idl_proto_private_privvate_proto_rawDescGZIP() []byte {
	file_idl_proto_private_privvate_proto_rawDescOnce.Do(func() {
		file_idl_proto_private_privvate_proto_rawDescData = protoimpl.X.CompressGZIP(file_idl_proto_private_privvate_proto_rawDescData)
	})
	return file_idl_proto_private_privvate_proto_rawDescData
}

var file_idl_proto_private_privvate_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_idl_proto_private_privvate_proto_goTypes = []interface{}{
	(*AutoLabelReq)(nil),  // 0: proto.AutoLabelReq
	(*AutoLabelResp)(nil), // 1: proto.AutoLabelResp
	(*BaseResp)(nil),      // 2: proto.BaseResp
}
var file_idl_proto_private_privvate_proto_depIdxs = []int32{
	2, // 0: proto.AutoLabelResp.base_resp:type_name -> proto.BaseResp
	0, // 1: proto.AutoLabel.AutoLabelAddTask:input_type -> proto.AutoLabelReq
	1, // 2: proto.AutoLabel.AutoLabelAddTask:output_type -> proto.AutoLabelResp
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_idl_proto_private_privvate_proto_init() }
func file_idl_proto_private_privvate_proto_init() {
	if File_idl_proto_private_privvate_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_idl_proto_private_privvate_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AutoLabelReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idl_proto_private_privvate_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AutoLabelResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idl_proto_private_privvate_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BaseResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_idl_proto_private_privvate_proto_msgTypes[0].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_idl_proto_private_privvate_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_idl_proto_private_privvate_proto_goTypes,
		DependencyIndexes: file_idl_proto_private_privvate_proto_depIdxs,
		MessageInfos:      file_idl_proto_private_privvate_proto_msgTypes,
	}.Build()
	File_idl_proto_private_privvate_proto = out.File
	file_idl_proto_private_privvate_proto_rawDesc = nil
	file_idl_proto_private_privvate_proto_goTypes = nil
	file_idl_proto_private_privvate_proto_depIdxs = nil
}
